services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    network_mode: container:vpn_general
    volumes:
      - /mnt/container_data/vaultwarden:/data
    environment:
      - WEBSOCKET_ENABLED=true
      - WEB_VAULT_ENABLED=true
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - ROCKET_PORT=8558
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.tls.certresolver=stepca"
      - "traefik.http.routers.vaultwarden.rule=Host(`bitwarden.$MY_DOMAIN`)"
      - "traefik.http.routers.vaultwarden-websocket.rule=Host(`bitwarden.$MY_DOMAIN`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=8558"
    restart: unless-stopped

  vw_backup:
    image: bruceforce/vaultwarden-backup:latest
    container_name: vw_backup
    depends_on:
      - vaultwarden
    volumes:
      - /mnt/container_data/vaultwarden:/data
      - /home/${USER1}/vw_backups:/backup
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_FILE=/data/db.sqlite3
      - BACKUP_FILE=/backup/backup.sqlite3
      - BACKUP_FILE_PERMISSIONS=700
      - CRON_TIME=0 1 * * *
      - TIMESTAMP=false
      - UID=0
      - GID=0
      - TZ=${TZ}
    restart: on-failure
